name: simple_messenger
version: 1.0.1
description: >-
  A very simple console-based implementation of a messages messenger in Dart
author: Peter Loos <peter.loos@gmx.de>
homepage: http://peterloos.de
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
